language: node_js
node_js: 
  - "stable"
before_script: 
  - cd Api
  - npm install
  - chmod 0755 node_modules/.bin/mocha
script:  
  - npm run test:travis
cache:
  directories:
    - "Api/node_modules"